/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fun_learnlife_ogglib_OggLib */

#ifndef _Included_fun_learnlife_ogglib_OggLib
#define _Included_fun_learnlife_ogglib_OggLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fun_learnlife_ogglib_OggLib
 * Method:    encode
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_fun_learnlife_ogglib_OggLib_encode
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     fun_learnlife_ogglib_OggLib
 * Method:    wavToOgg
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fun_learnlife_ogglib_OggLib_wavToOgg
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
